#!/usr/bin/env bun
/**
 * Regenerates docs/makeit/FEATURES.md and docs/makeit/features-index.json
 * from the YAML frontmatter of docs/makeit/features/*.md.
 *
 * The frontmatter is the single source of truth; both indexes are derived
 * and must never be hand-edited.
 *
 * Usage: bun scripts/gen-index.ts [project-root]
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type Feature = {
  id: string;
  title: string;
  tag: string;
  slice: string;
  status: string;
  deps: string[];
  path: string;
};

export function parseFrontmatter(raw: string): Record<string, string> {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fields: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const m = line.match(/^(\w[\w-]*):\s*(.*?)\s*(?:#.*)?$/);
    if (m) fields[m[1]] = m[2];
  }
  return fields;
}

export function collectFeatures(root: string): Feature[] {
  const featuresDir = join(root, "docs/makeit/features");
  return readdirSync(featuresDir)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const fm = parseFrontmatter(
        readFileSync(join(featuresDir, file), "utf8"),
      );
      return {
        id: fm.id ?? file.replace(/\.md$/, ""),
        title: fm.title ?? "(untitled)",
        tag: fm.tag ?? "must",
        slice: fm.slice ?? "(unassigned)",
        status: fm.status ?? "inventoried",
        deps: (fm.deps ?? "[]")
          .replace(/[\[\]\s]/g, "")
          .split(",")
          .filter(Boolean),
        path: `docs/makeit/features/${file}`,
      };
    })
    .sort(
      (a, b) => a.slice.localeCompare(b.slice) || a.id.localeCompare(b.id),
    );
}

export function renderMarkdown(features: Feature[]): string {
  const count = (tag: string) => features.filter((f) => f.tag === tag).length;
  let md = `# Features Index

> GENERATED by \`scripts/gen-index.ts\` - never hand-edit. Edit feature frontmatter, then regenerate.

| Total | must | should | wont | out-of-scope |
|---|---|---|---|---|
| ${features.length} | ${count("must")} | ${count("should")} | ${count("wont")} | ${count("out-of-scope")} |
`;
  const bySlice = Map.groupBy(features, (f) => f.slice);
  for (const [slice, items] of bySlice) {
    md += `\n## ${slice}\n\n| Id | Title | Tag | Status | Deps | Path |\n|---|---|---|---|---|---|\n`;
    for (const f of items) {
      md += `| ${f.id} | ${f.title} | ${f.tag} | ${f.status} | ${f.deps.join(", ") || "-"} | ${f.path} |\n`;
    }
  }
  return md;
}

export function generate(root: string): number {
  const docsDir = join(root, "docs/makeit");
  const features = collectFeatures(root);
  writeFileSync(
    join(docsDir, "features-index.json"),
    JSON.stringify(features, null, 2) + "\n",
  );
  writeFileSync(join(docsDir, "FEATURES.md"), renderMarkdown(features));
  return features.length;
}

if (import.meta.main) {
  const root = process.argv[2] ?? process.cwd();
  const n = generate(root);
  console.log(`Indexed ${n} features.`);
}
