#!/usr/bin/env bun
/**
 * Regenerates docs/makeit/FEATURES.md and docs/makeit/features-index.json
 * from the YAML frontmatter of docs/makeit/features/*.md.
 *
 * The frontmatter is the single source of truth; both indexes are derived
 * and must never be hand-edited.
 *
 * Usage: bun scripts/gen-index.ts [project-root]
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type Feature = {
  id: string;
  title: string;
  tag: string;
  slice: string;
  status: string;
  deps: string[];
  milestone: string;
  path: string;
};

export function parseFrontmatter(raw: string): Record<string, string> {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fields: Record<string, string> = {};
  for (const line of match[1].split("\n")) {
    const m = line.match(/^(\w[\w-]*):\s*(.*?)\s*(?:#.*)?$/);
    if (m) fields[m[1]] = m[2];
  }
  return fields;
}

export function collectFeatures(root: string): Feature[] {
  const featuresDir = join(root, "docs/makeit/features");
  return readdirSync(featuresDir)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const fm = parseFrontmatter(
        readFileSync(join(featuresDir, file), "utf8"),
      );
      return {
        id: fm.id ?? file.replace(/\.md$/, ""),
        title: fm.title ?? "(untitled)",
        tag: fm.tag ?? "must",
        slice: fm.slice ?? "(unassigned)",
        status: fm.status ?? "inventoried",
        deps: (fm.deps ?? "[]")
          .replace(/[\[\]\s]/g, "")
          .split(",")
          .filter(Boolean),
        milestone: (fm.milestone ?? "").replace(/^["']|["']$/g, ""),
        path: `docs/makeit/features/${file}`,
      };
    })
    .sort(
      (a, b) => a.slice.localeCompare(b.slice) || a.id.localeCompare(b.id),
    );
}

export function renderMarkdown(features: Feature[]): string {
  const count = (tag: string) => features.filter((f) => f.tag === tag).length;
  let md = `# Features Index

> GENERATED by \`scripts/gen-index.ts\` - never hand-edit. Edit feature frontmatter, then regenerate.

| Total | must | should | wont | out-of-scope |
|---|---|---|---|---|
| ${features.length} | ${count("must")} | ${count("should")} | ${count("wont")} | ${count("out-of-scope")} |
`;
  const bySlice = Map.groupBy(features, (f) => f.slice);
  for (const [slice, items] of bySlice) {
    md += `\n## ${slice}\n\n| Id | Title | Tag | Status | Deps | Milestone | Path |\n|---|---|---|---|---|---|---|\n`;
    for (const f of items) {
      md += `| ${f.id} | ${f.title} | ${f.tag} | ${f.status} | ${f.deps.join(", ") || "-"} | ${f.milestone || "-"} | ${f.path} |\n`;
    }
  }
  return md;
}

export const VALID_TAGS = new Set(["must", "should", "wont", "out-of-scope"]);
export const VALID_STATUSES = new Set([
  "inventoried",
  "spec-ready",
  "implementing",
  "integrated",
  "polished",
  "failed",
  "blocked-on-human",
  "already-built",
]);

/**
 * Validates the feature set: enum values, duplicate ids, dangling deps, and
 * dependency cycles (a cycle would deadlock Phase 4 wave planning).
 * Returns a list of error strings; empty means valid.
 */
export function validateFeatures(features: Feature[]): string[] {
  const errors: string[] = [];
  const byId = new Map<string, Feature>();

  for (const f of features) {
    if (byId.has(f.id)) {
      errors.push(`duplicate id ${f.id}: ${byId.get(f.id)!.path} and ${f.path}`);
    } else {
      byId.set(f.id, f);
    }
    if (!VALID_TAGS.has(f.tag)) {
      errors.push(`${f.id}: invalid tag "${f.tag}" (${f.path})`);
    }
    if (!VALID_STATUSES.has(f.status)) {
      errors.push(`${f.id}: invalid status "${f.status}" (${f.path})`);
    }
  }

  for (const f of features) {
    for (const dep of f.deps) {
      if (!byId.has(dep)) {
        errors.push(`${f.id}: dep "${dep}" does not exist (${f.path})`);
      }
    }
  }

  // Cycle detection via iterative DFS (white/gray/black coloring)
  const color = new Map<string, number>(); // 0 white, 1 gray, 2 black
  const visit = (start: string) => {
    const stack: Array<{ id: string; i: number; trail: string[] }> = [
      { id: start, i: 0, trail: [start] },
    ];
    color.set(start, 1);
    while (stack.length) {
      const top = stack[stack.length - 1];
      const deps = byId.get(top.id)?.deps.filter((d) => byId.has(d)) ?? [];
      if (top.i < deps.length) {
        const next = deps[top.i++];
        const c = color.get(next) ?? 0;
        if (c === 1) {
          errors.push(`dependency cycle: ${[...top.trail, next].join(" -> ")}`);
        } else if (c === 0) {
          color.set(next, 1);
          stack.push({ id: next, i: 0, trail: [...top.trail, next] });
        }
      } else {
        color.set(top.id, 2);
        stack.pop();
      }
    }
  };
  for (const id of byId.keys()) {
    if ((color.get(id) ?? 0) === 0) visit(id);
  }

  return errors;
}

/**
 * Validates, then writes both indexes. Throws on validation errors -
 * a broken graph must never produce a plausible-looking index.
 */
export function generate(root: string): number {
  const docsDir = join(root, "docs/makeit");
  const features = collectFeatures(root);
  const errors = validateFeatures(features);
  if (errors.length) {
    throw new Error(`feature validation failed:\n  ${errors.join("\n  ")}`);
  }
  writeFileSync(
    join(docsDir, "features-index.json"),
    JSON.stringify(features, null, 2) + "\n",
  );
  writeFileSync(join(docsDir, "FEATURES.md"), renderMarkdown(features));
  return features.length;
}

if (import.meta.main) {
  const checkOnly = process.argv.includes("--check");
  const root = process.argv.filter((a) => a !== "--check")[2] ?? process.cwd();
  if (checkOnly) {
    const errors = validateFeatures(collectFeatures(root));
    if (errors.length) {
      console.error(`INVALID:\n  ${errors.join("\n  ")}`);
      process.exit(1);
    }
    console.log("Feature graph valid.");
  } else {
    const n = generate(root);
    console.log(`Indexed ${n} features.`);
  }
}
